### ISSUE TITLE
Security Slam 2023 umbrella issue

### ISSUE THREAD

**Issue by matthyx** [kubescape/node-agent#128]
### Summary

**Repository**: node-agent
**URL**: https://github.com/kubescape/node-agent
**Checks sets**:  `CODE`
**Score**: 75

### Checks passed per category

| Category       |                                           Score |
| :------------- | ----------------------------------------------: |
| Documentation  |  76% |
| License        |        100% |
| Best Practices | 63% |
| Security       |       63% |
| Legal          |          n/a |

### Documentation [76%]

  - [x] Changelog ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [ ] Contributing ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/kubescape/node-agent/blob/main/MAINTAINERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/kubescape/node-agent/blob/main/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [100%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#spdx-id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#approved-license))
  - [x] [License scanning](https://app.fossa.com/projects/git%2Bgithub.com%2Fkubescape%2Fsniffer?ref=badge_shield&issueType=license) ([_docs_](https://clomonitor.io/docs/topics/checks/#license-scanning))
  
### Best Practices [63%]

  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifact-hub-badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin))
  - [ ] OpenSSF best practices badge ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf-badge))
  - [x] [OpenSSF Scorecard badge](https://api.securityscorecards.dev/projects/github.com/kubescape/node-agent) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge))
  - [x] [Recent release](https://github.com/kubescape/node-agent/releases/tag/v0.1.107) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent-release))
  
### Security [63%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary-artifacts-from-openssf-scorecard))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code-review-from-openssf-scorecard))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous-workflow-from-openssf-scorecard))
  - [ ] Dependencies policy ([_docs_](https://clomonitor.io/docs/topics/checks/#dependencies-policy)) `CHECK FAILED`
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency-update-tool-from-openssf-scorecard))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained-from-openssf-scorecard))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom))
  - [ ] Security insights ([_docs_](https://clomonitor.io/docs/topics/checks/#security-insights)) `CHECK FAILED`
  - [x] [Security policy](https://github.com/kubescape/node-agent/blob/main/SECURITY-INSIGHTS.yml) ([_docs_](https://clomonitor.io/docs/topics/checks/#security-policy))
  - [ ] Self-Assessment ([_docs_](https://clomonitor.io/docs/topics/checks/#self-assessment)) `CHECK FAILED`
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard))
  - [ ] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).
